# utils/response_generator.py
from openai import AsyncAzureOpenAI
from typing import List, Dict, Any
from config import (
    AZURE_OPENAI_API_KEY, AZURE_OPENAI_ENDPOINT, 
    AZURE_API_VERSION, AZURE_DEPLOYMENT_NAME
)
from langsmith import traceable

class ResponseGenerator:
    def __init__(self):
        self.client = AsyncAzureOpenAI(
            api_key=AZURE_OPENAI_API_KEY,
            azure_endpoint=AZURE_OPENAI_ENDPOINT,
            api_version=AZURE_API_VERSION,
        )

    @traceable(name="generate_answer_for_subquery")
    async def generate_answer_for_subquery(self, query: str, context_chunks: List[Dict[str, Any]]) -> str:
        """Generate answer for a single sub-query"""
        if not context_chunks:
            return "No relevant information found for this query."

        # Prepare context
        context_parts = []
        for i, chunk in enumerate(context_chunks):
            page = chunk.get("page_number", "N/A")
            chunk_type = chunk.get("type", "text")
            content = chunk.get("content", "").strip()
            if not content:
                continue
            if chunk_type == "text":
                context_parts.append(f"Text {i+1} (Page {page}):\n{content}")
            elif chunk_type == "table":
                context_parts.append(f"Table {i+1} (Page {page}):\n{content}")
            elif chunk_type == "image":
                # For images, the 'content' field holds the caption generated by the ImageCaptioner
                caption = content
                context_parts.append(f"Image {i+1} (Page {page}):\n{caption}")

        if not context_parts:
             return "No relevant content found in the retrieved context."

        context_text = "\n\n".join(context_parts)

        prompt = f"""
        BBased on the following context, answer the user's question.
        Context:
        {context_text}
        Question: {query}
        Instructions:
        - Answer **only** from the provided context
        - Cite page numbers when relevant (e.g., "According to page 5...")
        - If information is missing, state so clearly
        """

        try:
            response = await self.client.chat.completions.create(
                model=AZURE_DEPLOYMENT_NAME,
                messages=[
                    {"role": "system", "content": "You are a helpful assistant that answers questions based only on the provided context."},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.3
            )
            return response.choices[0].message.content.strip()
        except Exception as e:
            print(f"❌ Error generating answer for sub-query '{query}': {e}")
            return f"Error generating answer for sub-query: {query}"

    @traceable(name="combine_sub_answers")
    async def combine_sub_answers(self, original_query: str, sub_query_answers: List[Dict[str, Any]]) -> Dict[str, Any]:
        """
        Combine answers from sub-queries into a final coherent answer.
        Also return referenced images.
        """
        if not sub_query_answers:
            return {
                "answer": "No relevant information found to answer the question.",
                "images": []
            }

        # Build answer context and collect images
        answer_parts = []
        referenced_images = []

        for item in sub_query_answers:
             # Add the sub-question and its answer
             answer_parts.append(f"Sub-question: {item['sub_query']}\nAnswer: {item['answer']}")

             # Collect images mentioned in the *context* of this sub-answer
             for chunk in item.get("context", []): # Safely get 'context'
                 if chunk.get("type") == "image" and "image_path" in chunk:
                     # Convert path for web access if needed (adjust path logic as needed)
                     image_path = chunk["image_path"]
                     
                     # Assuming images are saved under data/ and served via /static/
                     if "data/" in image_path:
                         web_path = image_path.replace("data/", "/static/").replace("\\", "/")
                         referenced_images.append({
                             "url": web_path,
                             "page": chunk["page_number"],
                             "caption": chunk["content"] # Caption is stored in 'content' for images
                         })

        if not answer_parts:
             return {
                "answer": "No relevant information found to synthesize an answer.",
                "images": []
            }

        full_context = "\n\n".join(answer_parts)

        # Final synthesis prompt
        prompt = f"""
        You are tasked with combining multiple sub-answers into one comprehensive, coherent response.

        Original Question: {original_query}

        Sub-Question Answers:
        {full_context}

        Instructions:
        1. Synthesize the sub-answers into one comprehensive response
        2. Ensure the final answer directly addresses the original question
        3. Maintain consistency and avoid contradictions
        4. Include all relevant information from the sub-answers
        5. Present the information in a logical, well-structured manner
        6. If sub-answers complement each other, integrate them smoothly
        7. If there are any conflicts, note them appropriately

        Provide a comprehensive final answer:
        """

        try:
            response = await self.client.chat.completions.create(
                model=AZURE_DEPLOYMENT_NAME,
                messages=[
                    {"role": "system", "content": "You are a helpful assistant that synthesizes information from multiple sources to answer a complex question."},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.3
            )
            final_answer = response.choices[0].message.content.strip()
        except Exception as e:
            error_msg = f"Error in final synthesis: {e}"
            print(f"❌ {error_msg}")
            final_answer = f"Unable to generate a final answer due to an internal error: {str(e)}"

        return {
            "answer": final_answer,
            "images": referenced_images # Return collected images
        }

    # Add async context manager methods for 'async with'
    async def __aenter__(self):
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        await self.client.close()
